### ISSUE TITLE
Create React frontend client

### ISSUE THREAD

**Issue by CharlesAHunt** [Headstorm/shukra#1]
We need a Vue front end client to consume Akka Management HTTP endpoints to collect metric data on the Akka Cluster

**Comment by kpasagada** [comment]
https://headstorm.atlassian.net/wiki/spaces/KB/pages/987332630/UI+Framework+Matrix

This document goes over the pros and cons of different UI frameworks (Angular, React, Vue) for developing Shukra UI.

**Comment by kpasagada** [comment]
Shukra UI design:
https://www.figma.com/file/nrPyr74UCwjnkzLaJb732D/ShukraUI?node-id=0%3A1
