### ISSUE TITLE
Upgrade Scala to 2.13 and Akka to 2.6

### ISSUE THREAD

**Issue by CharlesAHunt** [Headstorm/shukra#15]
We need to upgrade Scala to 2.13 and Akka to 2.6

- Scala is upgraded to 2.13 in the SBT and the Gradle build

- Akka is upgraded to 2.6 in the SBT and the Gradle build

**Comment by kpasagada** [comment]
May also need to upgrade akka-management from 1.0.3 to 1.0.4
https://doc.akka.io/docs/akka-management/current/akka-management.html

Migration document:
https://doc.akka.io/docs/akka/2.6/project/migration-guide-2.5.x-2.6.x.html?_ga=2.120789768.1213060305.1573687976-622960681.1569340143
