### ISSUE TITLE
Update git documentation to include additional setup information

### ISSUE THREAD

**Issue by kpasagada** [Headstorm/shukra#54]
- Update the readme.md file to reflect missing virtual box installation instructions for vagrant
- Add notes to the same file (or not) to provide detailed instructions for Shukra setup
- Update the same file to reflect Zac as contributor

**Comment by zromick** [comment]
Assigning to myself through this comment.
Will also try to include a brief definition of Shukra: https://en.wikipedia.org/wiki/Shukra
