### ISSUE TITLE
Graph shows multiple oldest nodes on auto refresh

### ISSUE THREAD

**Issue by kpasagada** [Headstorm/shukra#59]
Shukra graph view does not remove outdated oldest nodes from the cluster graph during auto refresh

**Comment by zromick** [comment]
Assigning to self

**Comment by kpasagada** [comment]
Why this bug occurred?
https://github.com/visjs/vis-network/issues/173
https://github.com/almende/vis/issues/2567

What was the fix?
The idea was to reset the oldest/leader node properties to its default node properties explicitly, instead of relying on the options property of the react-vis-graph framework to reset node properties.
